AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: test-queue-cfn
      MaximumMessageSize: 2048
      Tags:
        - Key: Name
          Value: test-queue-cfn
